
[[redirects]]
    from = "https://amyshackles.netlify.com/*"
    to = "https://amyshackles.com/:splat 301!"


[[redirects]]
    from = "/blog/*"
    to = "https://blog.amyshackles.com/:splat"
    status = 200

[[redirects]]
    from = "https://amyshackles.com/tags/*"
    to = "https://blog.amyshackles.com/tags/:splat"
    status = 200
    force = true

[[redirects]]
    from = "https://amyshackles.com/categories/*"
    to = "https://blog.amyshackles.com/categories/:splat"
    status = 200
    force = true

[[redirects]]
    from = "https://amyshackles.com/post/*"
    to = "https://blog.amyshackles.com/post/:splat"
    status = 200
    force = true

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "sameorigin"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer-when-downgrade"
    
[[headers]]
    for = "*.css"
    [headers.values]
        Cache-Control = "public, max-age=604800"